class AppSecrets{
  static const supabaseUrl ="https://fkihyjpjxrxpgmsnkzwt.supabase.co";
  static const supabaseAnnonKey ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZraWh5anBqeHJ4cGdtc25rend0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTgwODcyOTEsImV4cCI6MjAzMzY2MzI5MX0.P1jL-0iUFxjGZr7egvH5bKbn4yKMnH6seiKvh48_0TI";
}